### PR TITLE
StoryQ 2: StoryQ in Codap v3

### PR DESCRIPTION
**Pull request by tealefristoe**
This PR makes several updates to StoryQ to get it working in Codap v3. During development it wasn't clear if these changes were compatible with Codap v2, so the branch was kept separate from master. However, Bill tested this branch in v2, and everything seemed to work, so we're now merging into master and no longer supporting multiple versions of StoryQ.

### CODE REVIEW

**Comment by dougmartin** [comment]
@teale is the plan to merge this now or to keep it as an ongoing separate branch?  If it is going to be a separate branch we should keep the `-v3` suffix for this branch so it is easily seen in the plugin window title in CODAP 3.

**Comment by tealefristoe** [comment]
@dougmartin We're planning on merging this into master and only maintaining one branch for StoryQ moving forward. Bill tested this version in Codap v2 and everything worked well for him 👍

**Review by dougmartin — APPROVED** [review]
Looks good :+1:

**Review by kswenson — COMMENTED** [review]
👍 I don't have much context for the changes themselves, which have already been approved, but I approve the notion of merging the branches and only supporting one version moving forward.

**Pull request merged**
